import { useEffect, useMemo, useState } from "react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import PageHeader from "../../components/common/PageHeader";
import { projectService } from "../../services/projectService";
import {
  getLatestAssessment,
  deleteAssessment,
} from "../../services/assessmentService";

function AdminAssessmentsPage() {
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");
  const [search, setSearch] = useState("");
  const [riskFilter, setRiskFilter] = useState("ALL");

  const loadAdminAssessments = async () => {
    try {
      setLoading(true);
      setMessage("");

      const projectResponse = await projectService.getProjects();

      const projects = Array.isArray(projectResponse)
        ? projectResponse
        : Array.isArray(projectResponse?.projects)
        ? projectResponse.projects
        : Array.isArray(projectResponse?.data)
        ? projectResponse.data
        : [];

      const latestResults = await Promise.all(
        projects.map(async (project) => {
          try {
            const latest = await getLatestAssessment(project._id);
            return { project, assessment: latest };
          } catch {
            return { project, assessment: null };
          }
        })
      );

      setRows(latestResults);
    } catch (error) {
      setMessage(
        error?.message ||
          error?.response?.data?.message ||
          "Failed to load admin assessments"
      );
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAdminAssessments();
  }, []);

  const handleDelete = async (assessmentId) => {
    const ok = window.confirm("Are you sure you want to delete this assessment?");
    if (!ok) return;

    try {
      setMessage("");
      await deleteAssessment(assessmentId);
      setMessage("Assessment deleted successfully");
      await loadAdminAssessments();
    } catch (error) {
      setMessage(
        error?.message ||
          error?.response?.data?.message ||
          "Failed to delete assessment"
      );
    }
  };

  const handleDownloadProjectPdf = (project, assessment) => {
    if (!assessment) {
      setMessage("No assessment available for this project");
      return;
    }

    const doc = new jsPDF();
    const snapshot = assessment.snapshotId;

    const projectName = project?.title || project?.name || "Untitled Project";
    const projectType = project?.projectType || project?.type || "N/A";
    const location = project?.location?.address || "N/A";

    doc.setFontSize(18);
    doc.text("Project Risk Assessment Report", 14, 18);

    doc.setFontSize(10);
    doc.text(`Project: ${projectName}`, 14, 28);
    doc.text(`Project ID: ${project?._id || "N/A"}`, 14, 34);
    doc.text(`Generated At: ${new Date().toLocaleString()}`, 14, 40);

    autoTable(doc, {
      startY: 50,
      head: [["Project Detail", "Value"]],
      body: [
        ["Project Name", projectName],
        ["Project Type", projectType],
        ["Location", location],
        ["Assessment Date", assessment.createdAt ? new Date(assessment.createdAt).toLocaleString() : "N/A"],
        ["Model Version", assessment.modelVersion || "v1"],
      ],
      styles: { fontSize: 10 },
      headStyles: { fillColor: [15, 23, 42] },
    });

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 12,
      head: [["Risk Metric", "Value"]],
      body: [
        ["Overall Risk Score", `${assessment.riskScore ?? "-"} / 100`],
        ["Risk Level", assessment.riskLevel || "-"],
        ["Weather Score", assessment.weatherScore ?? 0],
        ["Flood Score", assessment.floodScore ?? 0],
        ["Earthquake Score", assessment.earthquakeScore ?? 0],
        ["Flood Base Input", assessment.floodBase ?? snapshot?.floodRiskIndex ?? "N/A"],
        [
          "Elevation Adjustment",
          assessment.elevation != null
            ? `${assessment.elevation} m`
            : snapshot?.elevation != null
            ? `${snapshot.elevation} m`
            : "N/A",
        ],
      ],
      styles: { fontSize: 10 },
      headStyles: { fillColor: [30, 41, 59] },
    });

    autoTable(doc, {
      startY: doc.lastAutoTable.finalY + 12,
      head: [["Calculation Logic", "Description"]],
      body: [
        ["Weather Score", "weatherScore = calcWeatherScore(snapshot)"],
        ["Flood Score", "floodScore = adjustFloodByElevation(floodBase, elevation)"],
        ["Earthquake Score", "earthquakeScore = calcEarthquakeScore(snapshot)"],
        ["Final Score", "riskScore = calcRiskScore(weatherScore, floodScore, earthquakeScore)"],
        ["Risk Level", "riskLevel = levelFromScore(riskScore)"],
      ],
      styles: { fontSize: 9 },
      headStyles: { fillColor: [51, 65, 85] },
    });

    doc.setFontSize(9);
    doc.text(
      "Generated by Component 3 - Risk Assessment & Scoring Engine",
      14,
      285
    );

    const safeName = projectName.replace(/[^a-z0-9]/gi, "-").toLowerCase();
    doc.save(`${safeName}-risk-assessment.pdf`);
  };

  const filteredRows = useMemo(() => {
    return rows.filter(({ project, assessment }) => {
      const projectName = (project?.title || project?.name || "").toLowerCase();
      const projectType = (project?.projectType || project?.type || "").toLowerCase();
      const projectLocation = (project?.location?.address || "").toLowerCase();

      const term = search.toLowerCase();

      const matchesSearch =
        !term ||
        projectName.includes(term) ||
        projectType.includes(term) ||
        projectLocation.includes(term);

      const level = assessment?.riskLevel || "NOT_ASSESSED";
      const matchesLevel = riskFilter === "ALL" ? true : level === riskFilter;

      return matchesSearch && matchesLevel;
    });
  }, [rows, search, riskFilter]);

  const stats = useMemo(() => {
    const assessed = rows.filter((row) => row.assessment);

    const lowRiskProjects = assessed.filter(
      (row) => row.assessment?.riskLevel === "LOW"
    ).length;

    const mediumRiskProjects = assessed.filter(
      (row) => row.assessment?.riskLevel === "MEDIUM"
    ).length;

    const highRiskProjects = assessed.filter(
      (row) => row.assessment?.riskLevel === "HIGH"
    ).length;

    const averageRiskScore =
      assessed.length > 0
        ? (
            assessed.reduce(
              (sum, row) => sum + (row.assessment?.riskScore || 0),
              0
            ) / assessed.length
          ).toFixed(1)
        : "0.0";

    const topRiskProject =
      [...assessed].sort(
        (a, b) =>
          (b.assessment?.riskScore || 0) - (a.assessment?.riskScore || 0)
      )[0] || null;

    return {
      totalProjects: rows.length,
      projectsAssessed: assessed.length,
      notAssessed: rows.length - assessed.length,
      lowRiskProjects,
      mediumRiskProjects,
      highRiskProjects,
      averageRiskScore,
      topRiskProject,
      completion:
        rows.length > 0 ? Math.round((assessed.length / rows.length) * 100) : 0,
    };
  }, [rows]);

  const badgeClass = (level) => {
    if (level === "HIGH") return "bg-red-100 text-red-700";
    if (level === "MEDIUM") return "bg-amber-100 text-amber-700";
    if (level === "LOW") return "bg-emerald-100 text-emerald-700";
    return "bg-slate-100 text-slate-500";
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Admin Assessments"
        description="Monitor assessment results, review project risk levels, and manage assessment records."
      />

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <StatCard title="Total Projects" value={stats.totalProjects} />
        <StatCard
          title="Projects Assessed"
          value={stats.projectsAssessed}
          color="text-sky-600"
        />
        <StatCard
          title="High Risk Projects"
          value={stats.highRiskProjects}
          color="text-rose-600"
        />
        <StatCard
          title="Average Risk Score"
          value={stats.averageRiskScore}
          color="text-orange-600"
        />
      </div>

      <div className="grid gap-5 xl:grid-cols-3">
        <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm xl:col-span-2">
          <div className="mb-5 flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
            <div>
              <h2 className="text-xl font-extrabold text-slate-900">
                Risk Monitoring Overview
              </h2>
              <p className="text-sm text-slate-500">
                Card summary of assessment coverage and risk distribution.
              </p>
            </div>

            <span className="rounded-full bg-slate-100 px-4 py-2 text-xs font-bold text-slate-600">
              {stats.completion}% Completed
            </span>
          </div>

          <div className="mb-6">
            <div className="mb-2 flex justify-between text-xs font-bold uppercase tracking-widest text-slate-400">
              <span>Assessment Completion</span>
              <span>
                {stats.projectsAssessed} / {stats.totalProjects}
              </span>
            </div>

            <div className="h-4 rounded-full bg-slate-100">
              <div
                className="h-4 rounded-full bg-slate-900"
                style={{ width: `${stats.completion}%` }}
              />
            </div>
          </div>

          <div className="grid gap-4 md:grid-cols-4">
            <RiskSummaryCard
              title="Low Risk"
              value={stats.lowRiskProjects}
              description="Safe projects"
              color="emerald"
            />

            <RiskSummaryCard
              title="Medium Risk"
              value={stats.mediumRiskProjects}
              description="Needs attention"
              color="amber"
            />

            <RiskSummaryCard
              title="High Risk"
              value={stats.highRiskProjects}
              description="Critical projects"
              color="rose"
            />

            <RiskSummaryCard
              title="Not Assessed"
              value={stats.notAssessed}
              description="Pending projects"
              color="slate"
            />
          </div>
        </div>

        <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          <h2 className="text-xl font-extrabold text-slate-900">
            Highest Risk Project
          </h2>
          <p className="mt-1 text-sm text-slate-500">
            Project with the highest latest risk score.
          </p>

          {stats.topRiskProject ? (
            <div className="mt-5 rounded-3xl border border-rose-100 bg-rose-50 p-5">
              <p className="text-sm font-extrabold text-slate-900">
                {stats.topRiskProject.project?.title ||
                  stats.topRiskProject.project?.name ||
                  "Untitled Project"}
              </p>

              <p className="mt-2 text-xs font-bold uppercase tracking-widest text-rose-500">
                Highest Current Risk
              </p>

              <div className="mt-5 flex items-end justify-between">
                <p className="text-6xl font-extrabold text-rose-600">
                  {stats.topRiskProject.assessment?.riskScore}
                </p>
                <p className="pb-2 text-xs font-bold text-rose-500">/ 100</p>
              </div>

              <div className="mt-4 h-3 rounded-full bg-white">
                <div
                  className="h-3 rounded-full bg-rose-500"
                  style={{
                    width: `${Math.min(
                      stats.topRiskProject.assessment?.riskScore || 0,
                      100
                    )}%`,
                  }}
                />
              </div>

              <div className="mt-4 flex items-center justify-between gap-2">
                <span
                  className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${badgeClass(
                    stats.topRiskProject.assessment?.riskLevel
                  )}`}
                >
                  {stats.topRiskProject.assessment?.riskLevel}
                </span>

                <button
                  onClick={() =>
                    handleDownloadProjectPdf(
                      stats.topRiskProject.project,
                      stats.topRiskProject.assessment
                    )
                  }
                  className="rounded-xl bg-white px-4 py-2 text-xs font-bold text-rose-600 shadow-sm hover:bg-rose-100"
                >
                  Download PDF
                </button>
              </div>
            </div>
          ) : (
            <div className="mt-5 rounded-2xl bg-slate-50 p-8 text-center">
              <p className="text-sm text-slate-500">
                No assessed projects available yet.
              </p>
            </div>
          )}
        </div>
      </div>

      <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
        <div className="flex flex-col gap-3 lg:flex-row">
          <input
            type="text"
            placeholder="Search by project, type, or location..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-slate-400"
          />

          <select
            value={riskFilter}
            onChange={(e) => setRiskFilter(e.target.value)}
            className="rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-slate-400"
          >
            <option value="ALL">All Risk Levels</option>
            <option value="LOW">LOW</option>
            <option value="MEDIUM">MEDIUM</option>
            <option value="HIGH">HIGH</option>
            <option value="NOT_ASSESSED">NOT ASSESSED</option>
          </select>

          <button
            onClick={loadAdminAssessments}
            className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white hover:bg-slate-800"
          >
            Sync
          </button>
        </div>
      </div>

      {message && (
        <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
          <p className="text-sm text-slate-600">{message}</p>
        </div>
      )}

      {loading ? (
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <p className="text-sm text-slate-500">Loading assessments...</p>
        </div>
      ) : (
        <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="mb-5 flex flex-col gap-2 md:flex-row md:items-center md:justify-between">
            <div>
              <h2 className="text-xl font-extrabold text-slate-900">
                Project Assessment Records
              </h2>
              <p className="text-sm text-slate-500">
                Professional card-based monitoring view for project risk results.
              </p>
            </div>

            <span className="rounded-full bg-slate-100 px-4 py-2 text-xs font-bold text-slate-600">
              {filteredRows.length} Records
            </span>
          </div>

          {filteredRows.length === 0 ? (
            <div className="rounded-2xl bg-slate-50 p-10 text-center">
              <p className="text-sm font-medium text-slate-500">
                No assessment records found
              </p>
            </div>
          ) : (
            <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
              {filteredRows.map(({ project, assessment }) => (
                <AssessmentProjectCard
                  key={project._id}
                  project={project}
                  assessment={assessment}
                  onDelete={handleDelete}
                  onDownloadPdf={handleDownloadProjectPdf}
                  badgeClass={badgeClass}
                />
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

function StatCard({ title, value, color = "text-slate-900" }) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
      <p className="text-xs font-bold uppercase tracking-[0.2em] text-slate-400">
        {title}
      </p>
      <p className={`mt-3 text-3xl font-extrabold ${color}`}>{value}</p>
    </div>
  );
}

function RiskSummaryCard({ title, value, description, color }) {
  const styles = {
    emerald: "border-emerald-200 bg-emerald-50 text-emerald-700",
    amber: "border-amber-200 bg-amber-50 text-amber-700",
    rose: "border-rose-200 bg-rose-50 text-rose-700",
    slate: "border-slate-200 bg-slate-50 text-slate-600",
  };

  return (
    <div className={`rounded-2xl border p-5 shadow-sm ${styles[color]}`}>
      <p className="text-xs font-bold uppercase tracking-widest">{title}</p>
      <p className="mt-3 text-4xl font-extrabold">{value}</p>
      <p className="mt-2 text-xs font-semibold opacity-80">{description}</p>
    </div>
  );
}

function AssessmentProjectCard({
  project,
  assessment,
  onDelete,
  onDownloadPdf,
  badgeClass,
}) {
  const projectName = project.title || project.name || "Untitled Project";
  const projectType = project.projectType || project.type || "N/A";
  const location = project.location?.address || "N/A";

  const score = assessment?.riskScore;
  const level = assessment?.riskLevel || "NOT ASSESSED";
  const scoreValue = Number(score || 0);
  const normalizedLevel = assessment?.riskLevel || "NOT_ASSESSED";

  const cardBorder =
    normalizedLevel === "HIGH"
      ? "border-rose-200"
      : normalizedLevel === "MEDIUM"
      ? "border-amber-200"
      : normalizedLevel === "LOW"
      ? "border-emerald-200"
      : "border-slate-200";

  const scoreColor =
    normalizedLevel === "HIGH"
      ? "text-rose-600"
      : normalizedLevel === "MEDIUM"
      ? "text-amber-600"
      : normalizedLevel === "LOW"
      ? "text-emerald-600"
      : "text-slate-400";

  const progressColor =
    normalizedLevel === "HIGH"
      ? "bg-rose-500"
      : normalizedLevel === "MEDIUM"
      ? "bg-amber-500"
      : normalizedLevel === "LOW"
      ? "bg-emerald-500"
      : "bg-slate-300";

  return (
    <div
      className={`rounded-3xl border ${cardBorder} bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-md`}
    >
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="line-clamp-2 text-base font-extrabold text-slate-900">
            {projectName}
          </h3>

          <p className="mt-1 text-xs font-bold uppercase tracking-widest text-slate-400">
            {projectType}
          </p>
        </div>

        <span
          className={`shrink-0 rounded-full px-3 py-1 text-xs font-bold ${badgeClass(
            normalizedLevel
          )}`}
        >
          {level}
        </span>
      </div>

      <div className="mt-5 rounded-2xl bg-slate-50 p-4">
        <p className="text-xs font-bold uppercase tracking-widest text-slate-400">
          Risk Metric
        </p>

        <div className="mt-2 flex items-end justify-between">
          <p className={`text-5xl font-extrabold ${scoreColor}`}>
            {score ?? "-"}
          </p>

          <p className="text-xs font-semibold text-slate-400">/ 100</p>
        </div>

        <div className="mt-4 h-2 rounded-full bg-white">
          <div
            className={`h-2 rounded-full ${progressColor}`}
            style={{ width: `${Math.min(scoreValue, 100)}%` }}
          />
        </div>
      </div>

      <div className="mt-5 space-y-3 text-sm">
        <div>
          <p className="text-xs font-bold uppercase tracking-widest text-slate-400">
            Geographical Node
          </p>
          <p className="mt-1 line-clamp-2 font-medium text-slate-700">
            {location}
          </p>
        </div>

        <div>
          <p className="text-xs font-bold uppercase tracking-widest text-slate-400">
            Last Pulse
          </p>
          <p className="mt-1 font-medium text-slate-700">
            {assessment?.createdAt
              ? new Date(assessment.createdAt).toLocaleString()
              : "-"}
          </p>
        </div>
      </div>

      <div className="mt-5 flex flex-col gap-2 border-t border-slate-100 pt-4 sm:flex-row sm:items-center sm:justify-between">
        <span className="text-xs font-semibold text-slate-400">
          {assessment?._id ? "Assessment available" : "Waiting for assessment"}
        </span>

        <div className="flex gap-2">
          {assessment?._id ? (
            <>
              <button
                onClick={() => onDownloadPdf(project, assessment)}
                className="rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white hover:bg-slate-800"
              >
                PDF
              </button>

              <button
                onClick={() => onDelete(assessment._id)}
                className="rounded-xl bg-red-50 px-4 py-2 text-xs font-bold text-red-600 hover:bg-red-100"
              >
                Delete
              </button>
            </>
          ) : (
            <span className="rounded-xl bg-slate-100 px-4 py-2 text-xs font-bold text-slate-400">
              No Action
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

export default AdminAssessmentsPage;